import { useState } from 'react';
import { Camera, Sparkles, X, Clock, Flame, ChevronRight, ChevronLeft, Check, Loader2, ShoppingCart, ChefHat, Type, AlertCircle, Copy, MessageCircle } from 'lucide-react';

export default function FridgeAI() {
  const [screen, setScreen] = useState('home'); // home, input, pantry, recipes, recipe-detail, shopping
  const [inputMode, setInputMode] = useState(null); // 'text' (photo coming in V2)
  const [ingredients, setIngredients] = useState([]);
  const [textInput, setTextInput] = useState('');
  const [pantryStaples, setPantryStaples] = useState({});
  const [recipes, setRecipes] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedRecipe, setSelectedRecipe] = useState(null);
  const [shoppingList, setShoppingList] = useState([]);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const PANTRY_STAPLES = [
    { name: 'Salt', emoji: '🧂' },
    { name: 'Pepper', emoji: '🌶️' },
    { name: 'Oil', emoji: '🫒' },
    { name: 'Garlic', emoji: '🧄' },
    { name: 'Ginger', emoji: '🫚' },
    { name: 'Onion', emoji: '🧅' },
    { name: 'Sugar', emoji: '🍬' },
    { name: 'Flour', emoji: '🌾' },
    { name: 'Butter', emoji: '🧈' },
    { name: 'Cumin', emoji: '🌰' },
    { name: 'Turmeric', emoji: '💛' },
    { name: 'Chili Powder', emoji: '🌶️' },
  ];

  const handleTextSubmit = () => {
    if (!textInput.trim()) return;
    const items = textInput.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    const formatted = items.map(name => ({
      name: name.charAt(0).toUpperCase() + name.slice(1).toLowerCase(),
      emoji: '🥗',
      confidence: 100,
    }));
    setIngredients(formatted);
    setScreen('pantry');
  };

  const removeIngredient = (idx) => {
    setIngredients(ingredients.filter((_, i) => i !== idx));
  };

  const togglePantry = (name) => {
    setPantryStaples(prev => ({ ...prev, [name]: !prev[name] }));
  };

  const generateRecipes = async () => {
    setIsGenerating(true);
    setError(null);
    const haveStaples = Object.keys(pantryStaples).filter(k => pantryStaples[k]);
    const allIngredients = [
      ...ingredients.map(i => i.name),
      ...haveStaples,
    ];

    try {
      const prompt = `You are a recipe generator. The user has these ingredients available: ${allIngredients.join(', ')}.

Generate 3 realistic, cookable recipes using primarily these ingredients. For each recipe, list ALL required ingredients (with amounts) and clearly mark which ones the user is MISSING (not in their available list).

Respond with ONLY a valid JSON object (no markdown, no explanations) in this exact structure:
{
  "recipes": [
    {
      "name": "Recipe name",
      "cuisine": "Indian/Italian/etc",
      "time_minutes": 30,
      "difficulty": "Easy/Medium/Hard",
      "calories": 420,
      "protein_grams": 22,
      "servings": 2,
      "match_percent": 95,
      "tags": ["Vegetarian", "Quick"],
      "ingredients_needed": [
        {"name": "Tomato", "amount": "2 medium", "have_it": true},
        {"name": "Cumin seeds", "amount": "1 tsp", "have_it": false}
      ],
      "missing_ingredients": ["Cumin seeds"],
      "steps": [
        "Step 1 description with timing if relevant",
        "Step 2 description"
      ],
      "tips": "One useful cooking tip"
    }
  ]
}

Make recipes diverse (different cuisines, different cooking methods, different times). Match_percent reflects how much of each recipe the user already has — recipes with no missing items should be 95-100%, recipes missing 1-2 items should be 75-90%. Provide 5-7 cooking steps per recipe. Be realistic with calorie estimates.`;

      const response = await window.claude.complete(prompt);
      const cleaned = response.replace(/```json|```/g, '').trim();
      const parsed = JSON.parse(cleaned);

      // Sort by match_percent descending
      const sorted = (parsed.recipes || []).sort((a, b) => b.match_percent - a.match_percent);
      setRecipes(sorted);
      setIsGenerating(false);
      setScreen('recipes');
    } catch (err) {
      setError('Could not generate recipes. Please try again.');
      setIsGenerating(false);
    }
  };

  const buildShoppingList = (recipe) => {
    const missing = recipe.ingredients_needed.filter(i => !i.have_it);
    setShoppingList(missing);
    setSelectedRecipe(recipe);
    setScreen('shopping');
  };

  const copyShoppingList = () => {
    const text = `🛒 Shopping list for ${selectedRecipe.name}:\n\n${shoppingList.map(i => `• ${i.name} — ${i.amount}`).join('\n')}\n\nGenerated by FridgeAI`;
    
    // Try modern clipboard API first
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }).catch(() => {
        fallbackCopy(text);
      });
    } else {
      fallbackCopy(text);
    }
  };

  const fallbackCopy = (text) => {
    // Fallback: create a temporary textarea, select, and copy
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.focus();
    textarea.select();
    try {
      document.execCommand('copy');
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      // Last resort: show the text in an alert so user can copy manually
      alert('Copy failed. Here is your shopping list:\n\n' + text);
    }
    document.body.removeChild(textarea);
  };

  const shareToWhatsApp = () => {
    const text = `🛒 Shopping list for ${selectedRecipe.name}:\n\n${shoppingList.map(i => `• ${i.name} — ${i.amount}`).join('\n')}`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const reset = () => {
    setScreen('home');
    setInputMode(null);
    setIngredients([]);
    setTextInput('');
    setPantryStaples({});
    setRecipes([]);
    setSelectedRecipe(null);
    setShoppingList([]);
    setError(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-stone-100 via-amber-50 to-orange-50 p-4 sm:p-8 font-sans">
      <div className="max-w-md mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center shadow-lg shadow-orange-200">
              <ChefHat className="w-5 h-5 text-white" strokeWidth={2.5} />
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tight text-stone-900">FridgeAI</h1>
              <p className="text-xs text-stone-500 -mt-0.5">Powered by Claude</p>
            </div>
          </div>
          {screen !== 'home' && (
            <button onClick={reset} className="text-xs font-bold text-stone-600 hover:text-orange-600">Restart</button>
          )}
        </div>

        {/* Phone Frame */}
        <div className="bg-stone-900 rounded-[2.5rem] p-3 shadow-2xl shadow-stone-400/40">
          <div className="bg-white rounded-[2rem] overflow-hidden h-[680px] relative flex flex-col">

            {/* Error banner */}
            {error && (
              <div className="bg-red-50 border-b border-red-200 px-4 py-2 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-red-600 flex-shrink-0" />
                <p className="text-xs text-red-700">{error}</p>
                <button onClick={() => setError(null)} className="ml-auto text-red-600">
                  <X className="w-3 h-3" />
                </button>
              </div>
            )}

            {/* HOME */}
            {screen === 'home' && (
              <div className="h-full flex flex-col bg-gradient-to-br from-orange-50 via-white to-amber-50 px-6 pt-12">
                <div>
                  <p className="text-sm text-stone-500">Hello there 👋</p>
                  <h2 className="text-3xl font-black text-stone-900 mt-1 leading-tight">What's<br/>for dinner?</h2>
                  <p className="text-sm text-stone-600 mt-2">Tell me what you have. I'll figure out the rest.</p>
                </div>

                <div className="flex-1 flex flex-col justify-center gap-3 py-6">
                  <button
                    onClick={() => { setInputMode('text'); setScreen('input'); }}
                    className="group bg-white border-2 border-stone-200 hover:border-orange-400 hover:shadow-lg rounded-3xl p-5 text-left transition-all"
                  >
                    <div className="flex items-center gap-4">
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center shadow-md">
                        <Type className="w-7 h-7 text-white" strokeWidth={2} />
                      </div>
                      <div className="flex-1">
                        <h3 className="font-black text-stone-900">Type ingredients</h3>
                        <p className="text-xs text-stone-500 mt-0.5">List what you have in the fridge</p>
                      </div>
                      <ChevronRight className="w-5 h-5 text-stone-400 group-hover:text-orange-500" />
                    </div>
                  </button>

                  <div className="bg-stone-50 border-2 border-dashed border-stone-200 rounded-3xl p-5 opacity-70">
                    <div className="flex items-center gap-4">
                      <div className="w-14 h-14 rounded-2xl bg-stone-200 flex items-center justify-center">
                        <Camera className="w-7 h-7 text-stone-400" strokeWidth={2} />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <h3 className="font-black text-stone-500">Snap your fridge</h3>
                          <span className="text-[9px] font-bold bg-amber-100 text-amber-800 px-1.5 py-0.5 rounded-full uppercase tracking-wide">Soon</span>
                        </div>
                        <p className="text-xs text-stone-400 mt-0.5">Photo recognition · V2</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pb-8 flex items-center justify-center gap-1.5 text-xs text-stone-500">
                  <Sparkles className="w-3 h-3 text-orange-500" />
                  <span>Real recipes • Real shopping list • Zero waste</span>
                </div>
              </div>
            )}

            {/* INPUT - TEXT MODE */}
            {screen === 'input' && inputMode === 'text' && (
              <div className="h-full flex flex-col">
                <div className="px-5 pt-12 pb-3 border-b border-stone-100">
                  <button onClick={() => setScreen('home')} className="text-xs font-bold text-stone-500 mb-2 flex items-center gap-1">
                    <ChevronLeft className="w-3 h-3" /> Back
                  </button>
                  <h2 className="text-xl font-black text-stone-900">What do you have?</h2>
                  <p className="text-xs text-stone-500 mt-1">Comma-separated or one per line</p>
                </div>

                <div className="flex-1 px-5 py-4 flex flex-col">
                  <textarea
                    value={textInput}
                    onChange={(e) => setTextInput(e.target.value)}
                    placeholder="e.g.&#10;Paneer, tomato, onion&#10;Bell pepper&#10;Spinach"
                    className="flex-1 w-full p-4 bg-stone-50 border-2 border-stone-200 focus:border-orange-400 rounded-2xl resize-none text-sm text-stone-900 placeholder-stone-400 outline-none"
                  />

                  <div className="mt-3 bg-amber-50 border border-amber-200 rounded-xl p-3">
                    <p className="text-xs text-amber-900">
                      💡 <strong>Tip:</strong> Just list the main ingredients. Don't worry about salt, oil, or spices — I'll ask about those next.
                    </p>
                  </div>
                </div>

                <div className="px-5 pb-8 pt-3 border-t border-stone-100">
                  <button
                    onClick={handleTextSubmit}
                    disabled={!textInput.trim()}
                    className="w-full bg-gradient-to-r from-orange-500 to-red-500 text-white font-black py-4 rounded-2xl shadow-lg shadow-orange-200 disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    Continue
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              </div>
            )}

            {/* PANTRY CHECK */}
            {screen === 'pantry' && (
              <div className="h-full flex flex-col">
                <div className="px-5 pt-12 pb-3 border-b border-stone-100">
                  <p className="text-xs font-bold text-orange-600 uppercase tracking-wider">Step 2 of 3</p>
                  <h2 className="text-xl font-black text-stone-900 mt-0.5">What about basics?</h2>
                  <p className="text-xs text-stone-500 mt-1">Tap everything you already have</p>
                </div>

                <div className="flex-1 overflow-y-auto px-5 py-4">
                  {/* Ingredients you added */}
                  <div className="mb-4">
                    <p className="text-xs font-bold text-stone-500 uppercase mb-2">Your ingredients ({ingredients.length})</p>
                    <div className="flex flex-wrap gap-2">
                      {ingredients.map((ing, i) => (
                        <button
                          key={i}
                          onClick={() => removeIngredient(i)}
                          className="bg-emerald-50 border border-emerald-200 rounded-full px-3 py-1.5 flex items-center gap-1.5"
                        >
                          <span>{ing.emoji}</span>
                          <span className="text-xs font-bold text-emerald-900">{ing.name}</span>
                          <X className="w-3 h-3 text-emerald-500" />
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="border-t border-stone-100 pt-4">
                    <p className="text-xs font-bold text-stone-500 uppercase mb-2">Pantry staples — do you have these?</p>
                    <div className="grid grid-cols-3 gap-2">
                      {PANTRY_STAPLES.map((item) => {
                        const have = pantryStaples[item.name];
                        return (
                          <button
                            key={item.name}
                            onClick={() => togglePantry(item.name)}
                            className={`p-2.5 rounded-2xl border-2 transition-all ${
                              have
                                ? 'bg-emerald-50 border-emerald-400'
                                : 'bg-white border-stone-200'
                            }`}
                          >
                            <div className="text-2xl">{item.emoji}</div>
                            <p className={`text-[10px] font-bold mt-1 ${have ? 'text-emerald-700' : 'text-stone-600'}`}>
                              {item.name}
                            </p>
                            {have && (
                              <div className="absolute top-1 right-1 bg-emerald-500 rounded-full w-4 h-4 flex items-center justify-center">
                                <Check className="w-2.5 h-2.5 text-white" strokeWidth={3} />
                              </div>
                            )}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                </div>

                <div className="px-5 pb-8 pt-3 border-t border-stone-100">
                  <button
                    onClick={generateRecipes}
                    disabled={ingredients.length === 0 || isGenerating}
                    className="w-full bg-gradient-to-r from-orange-500 to-red-500 text-white font-black py-4 rounded-2xl shadow-lg shadow-orange-200 disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Cooking up recipes...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        Generate Recipes
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}

            {/* RECIPES LIST */}
            {screen === 'recipes' && (
              <div className="h-full flex flex-col">
                <div className="px-5 pt-12 pb-3 border-b border-stone-100">
                  <p className="text-xs font-bold text-orange-600 uppercase tracking-wider">Step 3 of 3</p>
                  <h2 className="text-xl font-black text-stone-900 mt-0.5">Pick your dinner</h2>
                  <p className="text-xs text-stone-500 mt-1">{recipes.length} recipes from your ingredients</p>
                </div>

                <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
                  {recipes.map((r, i) => {
                    const missingCount = (r.missing_ingredients || []).length;
                    const colors = ['from-orange-400 to-red-500', 'from-emerald-400 to-teal-500', 'from-amber-400 to-orange-500'];
                    return (
                      <button
                        key={i}
                        onClick={() => { setSelectedRecipe(r); setScreen('recipe-detail'); }}
                        className="w-full bg-white rounded-2xl p-4 shadow-sm border border-stone-100 hover:shadow-lg hover:border-orange-200 transition-all text-left relative overflow-hidden"
                      >
                        <div className={`absolute top-0 left-0 w-1.5 h-full bg-gradient-to-b ${colors[i % 3]}`}></div>
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex-1 pr-2">
                            <h3 className="font-black text-stone-900 text-base leading-tight">{r.name}</h3>
                            <p className="text-xs text-stone-500 mt-0.5">{r.cuisine}</p>
                          </div>
                          <div className="bg-gradient-to-br from-orange-500 to-red-500 text-white rounded-lg px-2 py-0.5 flex-shrink-0">
                            <span className="text-[10px] font-bold">{r.match_percent}%</span>
                          </div>
                        </div>

                        <div className="flex flex-wrap gap-1 mb-2">
                          {(r.tags || []).map(t => (
                            <span key={t} className="text-[10px] font-semibold text-stone-600 bg-stone-100 px-2 py-0.5 rounded-full">{t}</span>
                          ))}
                        </div>

                        <div className="grid grid-cols-3 gap-2 mt-2 pt-2 border-t border-stone-100">
                          <div className="flex items-center gap-1">
                            <Clock className="w-3 h-3 text-stone-400" />
                            <span className="text-xs font-bold text-stone-900">{r.time_minutes}m</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <Flame className="w-3 h-3 text-stone-400" />
                            <span className="text-xs font-bold text-stone-900">{r.calories}cal</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <span className="text-[10px] font-bold text-stone-400">P:</span>
                            <span className="text-xs font-bold text-stone-900">{r.protein_grams}g</span>
                          </div>
                        </div>

                        {missingCount > 0 && (
                          <div className="mt-2 bg-amber-50 border border-amber-200 rounded-lg px-2.5 py-1.5 flex items-center gap-1.5">
                            <ShoppingCart className="w-3 h-3 text-amber-700" />
                            <span className="text-[10px] font-bold text-amber-900">Need {missingCount} more</span>
                          </div>
                        )}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* RECIPE DETAIL */}
            {screen === 'recipe-detail' && selectedRecipe && (
              <div className="h-full flex flex-col">
                <div className="bg-gradient-to-br from-orange-500 to-red-500 px-5 pt-12 pb-5 text-white">
                  <button onClick={() => setScreen('recipes')} className="text-xs font-bold text-white/80 mb-2 flex items-center gap-1">
                    <ChevronLeft className="w-3 h-3" /> All recipes
                  </button>
                  <h2 className="text-xl font-black leading-tight">{selectedRecipe.name}</h2>
                  <p className="text-xs text-white/80 mt-0.5">{selectedRecipe.cuisine} • {selectedRecipe.difficulty}</p>
                  <div className="flex gap-3 mt-3 text-xs">
                    <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{selectedRecipe.time_minutes} min</span>
                    <span className="flex items-center gap-1"><Flame className="w-3 h-3" />{selectedRecipe.calories} cal</span>
                    <span>•</span>
                    <span>{selectedRecipe.protein_grams}g protein</span>
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto px-5 py-4">
                  {/* Ingredients */}
                  <div className="mb-4">
                    <h4 className="text-xs font-bold text-stone-500 uppercase mb-2">Ingredients</h4>
                    <div className="space-y-1.5">
                      {(selectedRecipe.ingredients_needed || []).map((ing, i) => (
                        <div key={i} className={`flex items-center justify-between rounded-xl px-3 py-2 ${
                          ing.have_it ? 'bg-emerald-50' : 'bg-amber-50 border border-amber-200'
                        }`}>
                          <div className="flex items-center gap-2">
                            {ing.have_it ? (
                              <Check className="w-3.5 h-3.5 text-emerald-600" strokeWidth={3} />
                            ) : (
                              <ShoppingCart className="w-3.5 h-3.5 text-amber-600" />
                            )}
                            <span className={`text-sm font-bold ${ing.have_it ? 'text-emerald-900' : 'text-amber-900'}`}>{ing.name}</span>
                          </div>
                          <span className={`text-xs ${ing.have_it ? 'text-emerald-700' : 'text-amber-800'}`}>{ing.amount}</span>
                        </div>
                      ))}
                    </div>

                    {(selectedRecipe.missing_ingredients || []).length > 0 && (
                      <button
                        onClick={() => buildShoppingList(selectedRecipe)}
                        className="w-full mt-3 bg-amber-500 hover:bg-amber-600 text-white font-bold py-2.5 rounded-xl text-sm flex items-center justify-center gap-2"
                      >
                        <ShoppingCart className="w-4 h-4" />
                        Build shopping list ({selectedRecipe.missing_ingredients.length})
                      </button>
                    )}
                  </div>

                  {/* Steps */}
                  <div className="border-t border-stone-100 pt-4">
                    <h4 className="text-xs font-bold text-stone-500 uppercase mb-2">Instructions</h4>
                    <ol className="space-y-3">
                      {(selectedRecipe.steps || []).map((step, i) => (
                        <li key={i} className="flex gap-3">
                          <div className="flex-shrink-0 w-6 h-6 rounded-full bg-orange-500 text-white text-xs font-black flex items-center justify-center mt-0.5">
                            {i + 1}
                          </div>
                          <p className="text-sm text-stone-800 leading-relaxed">{step}</p>
                        </li>
                      ))}
                    </ol>
                  </div>

                  {/* Tip */}
                  {selectedRecipe.tips && (
                    <div className="mt-4 bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-200 rounded-2xl p-3">
                      <p className="text-xs font-bold text-amber-900 mb-1">💡 Chef's tip</p>
                      <p className="text-sm text-stone-700">{selectedRecipe.tips}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* SHOPPING LIST */}
            {screen === 'shopping' && (
              <div className="h-full flex flex-col">
                <div className="px-5 pt-12 pb-3 border-b border-stone-100">
                  <button onClick={() => setScreen('recipe-detail')} className="text-xs font-bold text-stone-500 mb-2 flex items-center gap-1">
                    <ChevronLeft className="w-3 h-3" /> Back to recipe
                  </button>
                  <h2 className="text-xl font-black text-stone-900">Shopping list</h2>
                  <p className="text-xs text-stone-500 mt-1">For {selectedRecipe?.name}</p>
                </div>

                <div className="flex-1 overflow-y-auto px-5 py-4">
                  <div className="bg-gradient-to-br from-amber-50 to-orange-50 border border-amber-200 rounded-2xl p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <ShoppingCart className="w-5 h-5 text-amber-700" />
                      <h3 className="font-black text-amber-900">{shoppingList.length} items to buy</h3>
                    </div>
                    <div className="space-y-2">
                      {shoppingList.map((item, i) => (
                        <div key={i} className="bg-white rounded-xl px-3 py-2.5 flex items-center justify-between shadow-sm">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full border-2 border-stone-300"></div>
                            <span className="text-sm font-bold text-stone-900">{item.name}</span>
                          </div>
                          <span className="text-xs text-stone-600 font-medium">{item.amount}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 bg-stone-50 rounded-2xl p-4">
                    <p className="text-xs font-bold text-stone-500 uppercase mb-2">Estimated total</p>
                    <div className="flex items-baseline gap-2">
                      <span className="text-2xl font-black text-stone-900">~₹{shoppingList.length * 45}</span>
                      <span className="text-xs text-stone-500">for {shoppingList.length} {shoppingList.length === 1 ? 'item' : 'items'}</span>
                    </div>
                    <p className="text-xs text-stone-500 mt-2">
                      Save this list and order from your preferred grocery app.
                    </p>
                  </div>
                </div>

                <div className="px-5 pb-8 pt-3 border-t border-stone-100 grid grid-cols-2 gap-2">
                  <button
                    onClick={copyShoppingList}
                    className={`font-bold py-3 rounded-2xl flex items-center justify-center gap-2 text-sm transition-colors ${
                      copied ? 'bg-emerald-600 text-white' : 'bg-stone-900 text-white'
                    }`}
                  >
                    {copied ? (
                      <>
                        <Check className="w-4 h-4" strokeWidth={3} />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        Copy
                      </>
                    )}
                  </button>
                  <button
                    onClick={shareToWhatsApp}
                    className="bg-emerald-500 text-white font-bold py-3 rounded-2xl flex items-center justify-center gap-2 text-sm"
                  >
                    <MessageCircle className="w-4 h-4" />
                    WhatsApp
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        <p className="text-center text-xs text-stone-500 mt-4">
          Built with React + Claude API • Open source on GitHub
        </p>
      </div>
    </div>
  );
}
